CREATE DATABASE QL_TRASUA1

USE QL_TRASUA1

CREATE TABLE SANPHAM (
    MASP INT PRIMARY KEY IDENTITY(1,1),  
    TENSP NVARCHAR(100) NOT NULL,         
    GIA DECIMAL(18, 2) NOT NULL,          
    KICHTHUOC NVARCHAR(50) NOT NULL,               
    DUONGDAN VARCHAR(500)                 
);

CREATE TABLE KHACHHANG (
    MAKH INT PRIMARY KEY IDENTITY(1,1),  
    TENKH NVARCHAR(100),        
    SODT NVARCHAR(20),          
    DIACHI NVARCHAR(200),
    THANHVIEN NVARCHAR(10),                 
);

CREATE TABLE CHUONGTRINH_KHUYENMAI
(
	MAKM INT PRIMARY KEY IDENTITY(1,1),
	TENKM NVARCHAR(100) NOT NULL,
	NGAYBD DATE,
	NGAYKT DATE,
	PHAMTRAM_KM FLOAT
)

CREATE TABLE NHANVIEN (
    MANV INT PRIMARY KEY IDENTITY(1,1),    
    TENNV NVARCHAR(100) NOT NULL,          
    QUYEN NVARCHAR(50) NOT NULL,           
    USERNAME NVARCHAR(50) NOT NULL,        
    PASSWORD NVARCHAR(50) NOT NULL         
);

CREATE TABLE DONHANG (
    MADH INT PRIMARY KEY IDENTITY(1,1),     
    MAKH INT NOT NULL, 
    MANV INT NOT NULL,                     
    NGAYLAP DATETIME NOT NULL,              
    TONGGIA DECIMAL(18, 2),
    MAKM INT,        
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
    FOREIGN KEY (MAKM) REFERENCES CHUONGTRINH_KHUYENMAI(MAKM)
);

CREATE TABLE CHITIETDONHANG (
    MADH INT NOT NULL,                     
    MASP INT NOT NULL,                     
    SOLUONG INT NOT NULL,                  
    GIA DECIMAL(18, 2) NULL,           
    FOREIGN KEY (MADH) REFERENCES DONHANG(MADH),   
    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
    CONSTRAINT PK_CHITIETDONHANG PRIMARY KEY (MADH, MASP)    
);


ALTER TABLE NHANVIEN
ALTER COLUMN QUYEN NVARCHAR(20) NULL


INSERT INTO CHUONGTRINH_KHUYENMAI (TENKM, NGAYBD, NGAYKT, PHAMTRAM_KM) 
VALUES (N'Khuyến Mãi Ngày Phụ Nữ Việt Nam', '2024-10-20', '2024-10-20', 0.04);

INSERT INTO CHUONGTRINH_KHUYENMAI (TENKM, NGAYBD, NGAYKT, PHAMTRAM_KM) 
VALUES (N'Khuyến Mãi Ngày Quốc Tế Nam Giới', '2024-11-19', '2024-11-19', 0.04);

INSERT INTO CHUONGTRINH_KHUYENMAI (TENKM, NGAYBD, NGAYKT, PHAMTRAM_KM) 
VALUES (N'Khuyến Mãi Thành Viên', NULL, NULL, 0.04);

INSERT INTO CHUONGTRINH_KHUYENMAI (TENKM, NGAYBD, NGAYKT, PHAMTRAM_KM) 
VALUES (N'Khuyến Mãi Ngày Giáng Sinh', '2024-12-24', '2024-12-25', 0.04);


SELECT * FROM CHUONGTRINH_KHUYENMAI


INSERT INTO SANPHAM (TENSP, GIA, KICHTHUOC, DUONGDAN)
VALUES (N'FREEZE SOCOLA', 55000, N'Lớn', 'D:\\cong nghe net nop Copy 2\\DoAnCongNghe.Net\\GUI_QL_TRASUA\\image\\asset 6.jpeg');

INSERT INTO SANPHAM (TENSP, GIA, KICHTHUOC, DUONGDAN)
VALUES (N'PHIN SỮA ĐÁ', 39000, N'Vừa', 'D:\\cong nghe net nop Copy 2\\DoAnCongNghe.Net\\GUI_QL_TRASUA\\image\\asset 42.jpeg');

INSERT INTO SANPHAM (TENSP, GIA, KICHTHUOC, DUONGDAN)
VALUES (N'PHIN SỮA NÓNG', 45000, N'Lớn', 'D:\\cong nghe net nop Copy 2\\DoAnCongNghe.Net\\GUI_QL_TRASUA\\image\\asset 35.jpeg');

INSERT INTO SANPHAM (TENSP, GIA, KICHTHUOC, DUONGDAN)
VALUES (N'TRÀ THẠCH ĐÀO', 45000, N'Vừa', 'D:\\cong nghe net nop Copy 2\\DoAnCongNghe.Net\\GUI_QL_TRASUA\\image\\asset 47.jpeg');

INSERT INTO SANPHAM (TENSP, GIA, KICHTHUOC, DUONGDAN)
VALUES (N'FREEZE TRÀ XANH', 59000, N'Lớn', 'D:\\cong nghe net nop Copy 2\\DoAnCongNghe.Net\\GUI_QL_TRASUA\\image\\asset 9.jpeg');

INSERT INTO SANPHAM (TENSP, GIA, KICHTHUOC, DUONGDAN)
VALUES (N'TRÀ XANH LATTE', 50000, N'Lớn', 'D:\\cong nghe net nop Copy 2\\DoAnCongNghe.Net\\GUI_QL_TRASUA\\image\\asset 50.jpeg');

INSERT INTO SANPHAM (TENSP, GIA, KICHTHUOC, DUONGDAN)
VALUES (N'BẠC SỈU', 35000, N'Vừa', 'D:\\cong nghe net nop Copy 2\\DoAnCongNghe.Net\\GUI_QL_TRASUA\\image\\asset 37.jpeg');

INSERT INTO SANPHAM (TENSP, GIA, KICHTHUOC, DUONGDAN)
VALUES (N'CARAMEL MACCHIATO', 59000, N'Lớn', 'D:\\cong nghe net nop Copy 2\\DoAnCongNghe.Net\\GUI_QL_TRASUA\\image\\asset 7.jpeg');

INSERT INTO SANPHAM (TENSP, GIA, KICHTHUOC, DUONGDAN)
VALUES (N'ESPRESSO', 35000, N'Nóng', 'D:\\cong nghe net nop Copy 2\\DoAnCongNghe.Net\\GUI_QL_TRASUA\\image\\asset 28.jpeg');

INSERT INTO SANPHAM (TENSP, GIA, KICHTHUOC, DUONGDAN)
VALUES (N'CÀ PHÊ SỮA ĐÁ', 40000, N'Vừa', 'D:\\cong nghe net nop Copy 2\\DoAnCongNghe.Net\\GUI_QL_TRASUA\\image\\asset 42.jpeg');

INSERT INTO SANPHAM (TENSP, GIA, KICHTHUOC, DUONGDAN)
VALUES (N'TRÀ BÔNG HỒNG', 45000, N'Vừa', 'D:\\cong nghe net nop Copy 2\\DoAnCongNghe.Net\\GUI_QL_TRASUA\\image\\asset 25.jpeg');

INSERT INTO SANPHAM (TENSP, GIA, KICHTHUOC, DUONGDAN)
VALUES (N'FREEZE TRÀ ĐEN', 55000, N'Lớn', 'D:\\cong nghe net nop Copy 2\\DoAnCongNghe.Net\\GUI_QL_TRASUA\\image\\asset 28.jpeg');

INSERT INTO SANPHAM (TENSP, GIA, KICHTHUOC, DUONGDAN)
VALUES (N'CÀ PHÊ ĐEN ĐÁ', 39000, N'Vừa', 'D:\\cong nghe net nop Copy 2\\DoAnCongNghe.Net\\GUI_QL_TRASUA\\image\\asset 32.jpeg');

INSERT INTO SANPHAM (TENSP, GIA, KICHTHUOC, DUONGDAN)
VALUES (N'CAFÉ VIỆT', 50000, N'Nóng', 'D:\\cong nghe net nop Copy 2\\DoAnCongNghe.Net\\GUI_QL_TRASUA\\image\\asset 44.jpeg');

INSERT INTO SANPHAM (TENSP, GIA, KICHTHUOC, DUONGDAN)
VALUES (N'TRÀ ĐEN ĐÁ', 35000, N'Vừa', 'D:\\cong nghe net nop Copy 2\\DoAnCongNghe.Net\\GUI_QL_TRASUA\\image\\asset 27.jpeg');

INSERT INTO SANPHAM (TENSP, GIA, KICHTHUOC, DUONGDAN)
VALUES (N'TRÀ GỪNG', 45000, N'Nóng', 'D:\\cong nghe net nop Copy 2\\DoAnCongNghe.Net\\GUI_QL_TRASUA\\image\\asset 14.jpeg');

INSERT INTO SANPHAM (TENSP, GIA, KICHTHUOC, DUONGDAN)
VALUES (N'FREEZE CÀ PHÊ', 60000, N'Lớn', 'D:\\cong nghe net nop Copy 2\\DoAnCongNghe.Net\\GUI_QL_TRASUA\\image\\asset 7.jpeg');

SELECT * FROM SANPHAM

--DROP TABLE KHACHHANG
--DROP TABLE DONHANG
--DROP TABLE CHITIETDONHANG


INSERT INTO KHACHHANG (TENKH, SODT, DIACHI, THANHVIEN) VALUES 
(N'Nguyễn Văn A', '0987654321', N'Hà Nội', N'Có'),
(NULL, NULL, NULL, N'Không'),
(NULL, NULL, NULL, N'Không'),
(NULL, NULL, NULL, N'Không'),
(NULL, NULL, NULL, N'Không');

INSERT INTO NHANVIEN (TENNV, QUYEN, USERNAME, PASSWORD) VALUES 
(N'Nguyễn Quản Lý', 'Admin', 'quanly01', 'nhanvien1'),
(N'Trần Bán Hàng', 'Nhân viên', 'nhanvien01', 'nhanvien2'),
(N'Phạm Hỗ Trợ', 'Nhân viên', 'nhanvien02', 'nhanvien3'),
(N'Lê Kế Toán', 'Nhân viên', 'nhanvien03', 'nhanvien4'),
(N'Hoàng Chủ Quán', 'Admin', 'admin01', 'nhanvien5');

INSERT INTO NHANVIEN (TENNV, QUYEN, USERNAME, PASSWORD) VALUES 
(N'Huỳnh Thanh Sơn', 'Admin', 'son', '123')
INSERT INTO NHANVIEN (TENNV, QUYEN, USERNAME, PASSWORD) VALUES 
(N'Trần Thị Yến Nhi', 'Admin', 'nhi', '123')

select * from NHANVIEN

INSERT INTO DONHANG (MAKH, NGAYLAP, MANV, MAKM) VALUES (1, '2024-10-12', 1, 3);
INSERT INTO DONHANG (MAKH, NGAYLAP, MANV, MAKM) VALUES (2, '2024-10-11', 2, NULL);
INSERT INTO DONHANG (MAKH, NGAYLAP, MANV, MAKM) VALUES (3, '2024-10-10', 1, NULL);
INSERT INTO DONHANG (MAKH, NGAYLAP, MANV, MAKM) VALUES (4, '2024-10-09', 2, NULL);
INSERT INTO DONHANG (MAKH, NGAYLAP, MANV, MAKM) VALUES (5, '2024-10-08', 1, NULL);
INSERT INTO DONHANG (MAKH, NGAYLAP, MANV, MAKM) VALUES (1, '2023-09-12', 2, 3);
INSERT INTO DONHANG (MAKH, NGAYLAP, MANV, MAKM) VALUES (1, '2024-10-08', 1, 3);
INSERT INTO DONHANG (MAKH, NGAYLAP, MANV, MAKM) VALUES (2, '2024-10-08', 2, NULL);
INSERT INTO DONHANG (MAKH, NGAYLAP, MANV, MAKM) VALUES (3, '2024-10-15', 1, NULL);
INSERT INTO DONHANG (MAKH, NGAYLAP, MANV, MAKM) VALUES (4, '2024-10-15', 2, NULL);
INSERT INTO DONHANG (MAKH, NGAYLAP, MANV, MAKM) VALUES (5, '2024-10-13', 1, NULL);
INSERT INTO DONHANG (MAKH, NGAYLAP, MANV, MAKM) VALUES (2, '2024-09-20', 2, NULL);
INSERT INTO DONHANG (MAKH, NGAYLAP, MANV, MAKM) VALUES (2, '2024-09-20', 1, NULL);
INSERT INTO DONHANG (MAKH, NGAYLAP, MANV, MAKM) VALUES (3, '2024-09-22', 1, NULL);

SELECT * FROM DONHANG

INSERT INTO CHITIETDONHANG (MADH, MASP, SOLUONG) VALUES (1, 1, 2);
INSERT INTO CHITIETDONHANG (MADH, MASP, SOLUONG) VALUES (1, 3, 1);
INSERT INTO CHITIETDONHANG (MADH, MASP, SOLUONG) VALUES (2, 3, 2);
INSERT INTO CHITIETDONHANG (MADH, MASP, SOLUONG) VALUES (2, 4, 1);
INSERT INTO CHITIETDONHANG (MADH, MASP, SOLUONG) VALUES (3, 5, 1);
INSERT INTO CHITIETDONHANG (MADH, MASP, SOLUONG) VALUES (3, 1, 1);
INSERT INTO CHITIETDONHANG (MADH, MASP, SOLUONG) VALUES (4, 3, 1);
INSERT INTO CHITIETDONHANG (MADH, MASP, SOLUONG) VALUES (5, 3, 2);
INSERT INTO CHITIETDONHANG (MADH, MASP, SOLUONG) VALUES (6, 5, 1);
INSERT INTO CHITIETDONHANG (MADH, MASP, SOLUONG) VALUES (7, 1, 2);
INSERT INTO CHITIETDONHANG (MADH, MASP, SOLUONG) VALUES (8, 4, 1);
INSERT INTO CHITIETDONHANG (MADH, MASP, SOLUONG) VALUES (8, 3, 1);
INSERT INTO CHITIETDONHANG (MADH, MASP, SOLUONG) VALUES (9, 4, 1);
INSERT INTO CHITIETDONHANG (MADH, MASP, SOLUONG) VALUES (9, 5, 2);
INSERT INTO CHITIETDONHANG (MADH, MASP, SOLUONG) VALUES (10, 3, 1);
INSERT INTO CHITIETDONHANG (MADH, MASP, SOLUONG) VALUES (10, 6, 1);
INSERT INTO CHITIETDONHANG (MADH, MASP, SOLUONG) VALUES (11, 8, 1);


/* INSERT INTO CHITIETDONHANG (MADH, MASP, SOLUONG) VALUES 
(7, 1, 2),
(7, 2, 1) */




-- SELECT
    SELECT * FROM NHANVIEN
    SELECT * FROM KHACHHANG
    SELECT * FROM SANPHAM
    SELECT * FROM DONHANG
    SELECT * FROM CHITIETDONHANG
    SELECT * FROM CHUONGTRINH_KHUYENMAI

-- DROP TABLE
    /*     DROP TABLE NHANVIEN
        DROP TABLE KHACHHANG
        DROP TABLE SANPHAM
        DROP TABLE DONHANG
        DROP TABLE CHITIETDONHANG */
-- 
    SELECT COUNT(*) FROM KHACHHANG
--
    SELECT DAY(NGAYLAP) FROM DONHANG
    GROUP BY DAY(NGAYLAP)

    SELECT NGAYLAP FROM DONHANG

    SELECT YEAR(NGAYLAP) FROM DONHANG GROUP BY YEAR(NGAYLAP)



    SELECT * FROM DONHANG WHERE DAY(NGAYLAP) = 12

    SELECT FORMAT(NGAYLAP, 'dd/MM/yyyy') AS NgayThangNam FROM DONHANG;

    SELECT FORMAT(NGAYLAP, 'MM/yyyy') AS ThangNam FROM DONHANG;


    SELECT SUM(TONGGIA) FROM DONHANG

    SELECT SUM(TONGGIA) FROM DONHANG WHERE YEAR(NGAYLAP) = 2024
    SELECT SUM(TONGGIA) FROM DONHANG WHERE MONTH(NGAYLAP) = 10 AND YEAR(NGAYLAP) = YEAR(GETDATE())
-- trigger xử lý đơn hàng và chi tiết đơn hàng
GO
    -- trigger tính gia trong donhang
    CREATE TRIGGER trg_UpdateChiTietDonHang
    ON CHITIETDONHANG
    AFTER INSERT, UPDATE
    AS
    BEGIN
        -- Tạo biến để lưu giá của sản phẩm
        DECLARE @MASP INT, @SOLUONG INT, @GIA DECIMAL(18, 2);

        -- Lấy thông tin từ bảng CHITIETDONHANG
        SELECT @MASP = MASP, @SOLUONG = SOLUONG
        FROM inserted;

        -- Lấy giá của sản phẩm từ bảng SANPHAM
        SELECT @GIA = GIA
        FROM SANPHAM
        WHERE MASP = @MASP;

        -- Cập nhật giá trong bảng CHITIETDONHANG
        UPDATE CHITIETDONHANG
        SET GIA = @GIA * @SOLUONG
        WHERE MASP = @MASP AND MADH = (SELECT MADH FROM inserted);
    END;



/*     DROP TRIGGER trg_UpdateChiTietDonHang
 */GO
/*     CREATE TRIGGER trg_UpdateChiTietDonHang
    ON CHITIETDONHANG
    AFTER INSERT, UPDATE
    AS
    BEGIN
        -- Cập nhật giá cho từng sản phẩm trong chi tiết đơn hàng
        UPDATE CTHD
        SET CTHD.GIA = SP.GIA * CTHD.SOLUONG
        FROM CHITIETDONHANG CTHD
        JOIN SANPHAM SP ON CTHD.MASP = SP.MASP
        WHERE CTHD.MADH IN (SELECT MADH FROM inserted);
    END;
    DROP TRIGGER trg_UpdateChiTietDonHang */


GO
    -- TRIGGER TÍNH TỔNG TIỀN DONHANG
    CREATE TRIGGER trg_UpdateTongTienDonHang
    ON CHITIETDONHANG
    AFTER INSERT, UPDATE, DELETE
    AS
    BEGIN
        DECLARE @MADH INT, @MAKM INT, @HESO FLOAT, @TONGGIA DECIMAL(18,2);

        -- Trường hợp INSERT hoặc UPDATE: Lấy mã đơn hàng từ bảng inserted
        IF EXISTS (SELECT 1 FROM inserted)
        BEGIN
            SELECT @MADH = MADH FROM inserted;
        END

        -- Trường hợp DELETE: Lấy mã đơn hàng từ bảng deleted
        IF EXISTS (SELECT 1 FROM deleted)
        BEGIN
            SELECT @MADH = MADH FROM deleted;
        END

        SET @MAKM = (SELECT MAKM FROM DONHANG WHERE MADH = @MADH)

        SET @HESO = (SELECT PHAMTRAM_KM FROM CHUONGTRINH_KHUYENMAI WHERE MAKM = @MAKM)

        SET @TONGGIA = (SELECT SUM(GIA) FROM CHITIETDONHANG WHERE MADH = @MADH)

        SET @TONGGIA = @TONGGIA - (@TONGGIA * @HESO)

        -- Cập nhật tổng giá trị đơn hàng trong bảng DONHANG
        UPDATE DONHANG
        SET TONGGIA = @TONGGIA
        WHERE MADH = @MADH;
    END;
GO
    DROP TRIGGER trg_UpdateTongTienDonHang
    
ALTER TABLE CHITIETDONHANG
ADD CONSTRAINT PK_CHITIETDONHANG PRIMARY KEY (MADH, MASP)

select Top 1 * from KHACHHANG ORDER BY MAKH DESC

    

